name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: yarn install
      env:
        CI: true

    - name: build
      run: yarn build
      env:
        CI: true

    - name: test
      run: yarn test
      env:
        CI: true
